### ISSUE TITLE
I git clone - but nothing shows up for numbers

### ISSUE THREAD

**Issue by arLevi** [synesthesiam/mnemofy#2]
What I've done is:
```
$ git clone https://github.com/synesthesiam/mnemofy
mnemofy$ python mnemofy.py 90210
# Numbers
$

$ python -V
Python 2.7.16
```

nothing ... any idea ?

**Comment by arLevi** [comment]
ok found the issue
Should be either:
(1)
Line: 137
Function get_words()
`words_dict[int(mnum)].append( (freq, word) )`
Instead of 
`words_dict[mnum].append( (freq, word) )`

OR
(2)
Line: 173
Function: main
`numbers = [unicode(item) for item in args.nums_or_words]`
Instead of
`numbers = [int(item) for item in args.nums_or_words]`


This is because the key - for some reason - is a unicode type vs int, and later we search by:
`for freq, word in sorted(words_dict[number], key=lambda fw: fw[0], reverse=True):`

**Comment by synesthesiam** [comment]
Thanks for catching this and providing a fix. As you can see, I haven't touched it in years. I wonder what changed to cause the problem *shrug*
